version: '3.8'
services:
  jack97:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3400:3000'
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    networks:
      - company-network
    restart: always
networks:
  company-network:
    driver: bridge
